Parameterized user home dir. With this change any user, not only xf11i…
NSLS2/chx-profile-collection pull request #15
Opened 2020-07-29 18:32 UTC by oksanagit

…d can ran scans. Tested as oksana

2020-07-29 20:08 UTC, mrakitin reviewed
Thanks for the contribution, @oksanagit! I left a minor improvement suggestion to stich the file path in the OS-independent way.

I noticed that the same hardcoded variable is used below within a function (see https://github.com/NSLS-II-CHX/profile_collection/pull/15/files#diff-30351e59d8b68c700d5d4c3fc2666a1dR322). I think we can just reuse the `directory` there. Could you please also make this change? Thanks.

2020-07-29 20:08 UTC, mrakitin commented on startup/99-bluesky.py
> +directory = os.path.expanduser("~") + "/specfiles/"
```suggestion
directory = os.path.join(os.path.expanduser("~"), "specfiles/")
```

2020-07-29 20:56 UTC, oksanagit commented
I made a change to line 329    from  
full_path='/home/xf11id/specfiles/'+name+'.spec'
to 
    full_path=os.path.join(os.path.expanduser("~", "specfiles/", name, '.spec')
How I can test it? The way i start bsui, this line never gets executed.

2020-07-30 16:02 UTC, mrakitin requested changes
In the original implementation there was a syntax error on line 329 with the missing closing parenthesis. I suggest to use the defined earlier `directory` var. The extension should be joined separately, as `os.path.join(...)` will join it with the path separators, `/` for Linux.

2020-07-30 16:02 UTC, mrakitin commented on startup/99-bluesky.py
> +    full_path=os.path.join(os.path.expanduser("~", "specfiles/", name, '.spec')
```suggestion
    full_path = os.path.join(directory, f'{name}.spec')
```

2020-07-30 16:30 UTC, mrakitin approved these changes

2020-07-30 16:32 UTC, mrakitin commented
I think it looks correct now.

@afluerasu, just to let you know that we fixed one hard-coded path here, to make it more portable.

2020-07-30 16:35 UTC, merged

2020-07-30 17:22 UTC, danielballan commented
Thanks @oksanagit!